select k.oznaka as 'oznaka',
 o.ID_osebe as 'kontrolor',
 o.naslov1 as 'naslov1',
 o.naslov2 as 'naslov2',
 k.metoda as 'metoda',
 k.kraj_kontrole as 'kraj_kontrole',
 k.datum_kontrole as 'datum_kontrole',
 k.datum_izdaje as 'datum_izdaje',
r.ID_rezultat as 'ID_rezultat',
r.Tip_vozila as 'tip_vozila',
r.Registrska_stevilka as 'registerska_stevilka',
r.Stevilka_sasije as 'stevilka_sasije',
r.Tip_taksimetra as 'tip_taksimetra',
r.Serijska_stevilka as 'serijska_stevilka',
r.Program as 'program',
r.Ohisje as 'ohisje',
r.Segmenti as 'segmenti',
r.Povezava as 'povezava',
r.Pnevmatike as 'pneomatike',
r.Tarife as 'tarife',
r.Realni_cas as 'realni_cas',
r.Nalepke as 'nalepke',
r.KonstantaW as 'konstantaW',
r.Kontrolna as 'kontrolna',
r.Stanje_stevca as 'stanje_stevca',
r.Cas_castesta as 'cas_castesta',
r.Cas_izmerjen as 'cas_izmerjen',
r.Cas_pogresek as 'cas_pogresek',
r.Pot_razdalja as 'pot_razdalja',
r.Pot_Impulzi as 'poz_impulzi',
r.Pot_izmerjen as 'pot_izmerjen',
r.Opombe as 'opombe'
from kontrola k
inner join oseba o on (ID_osebe),
inner join rezultat on (ID_rezultat)
