select 
v.Sifra_izdajatelj as 'izdajatelj',
v.Sifra_zaporedna as 'zaporedna',
v.Sifra_leto as 'leto',
v.Vrsta_posega as 'vrsta_poseg',
o.naziv as 'naziv_imetnika',
o.naslov1 as 'naslov1_imetnika',
o.naslov2 as 'naslov2_imetnika',
o1.naziv as 'naziv_izvajalec',
o1.naslov1 as 'naslov1_izvajalec',
o1.naslov2 as 'naslov2_izvajalec',
v.Vozilo_tip as 'tip_vozila',
v.Vozilo_sasija as 'sasija',
v.Vozilo_registrska as 'registrska',
v.Vozilo_konstantaW as 'konstantaW',
v.Pnevmatike_zadaj as 'pneomatike_zadaj',
v.Pnevmatike_spreda as 'pneomatike_spredaj',
t.oznaka as 'oznaka_takimetra',
t.tip as 'tip_taksimetra',
t.serijska as 'serijska_taksimetra',
t.program as 'program_taksimetra',
t.izracun as 'izracun_voznine',
t.prilagajanje_impulzov as 'impulzi',
v.Odgovorna_oseba as 'odgovorna_oseba',
v.Datum_posega as 'datum_posega',
v.Datum_izdaje as 'datum_izdaje'
from vgradnja_overjanje v
inner join oseba o on (v.ID_imetnik = o.ID_osebe),
inner join oseba o1 on (v.ID_izvajalec = o.ID_osebe),
inner join taksimeter t on (Oznaka)